export const themeRows = [
  {
    name: "Classic Craft",
    description: "Default Minecraft dark — stone & obsidian",
    primaryColor: "#5aaa38",
    backgroundColor: "#0e0e0e",
    textColor: "#e8e8e8",
    fontFamily: "var(--font-mc), monospace",
    isDefault: true,
  },
  {
    name: "Nether Fortress",
    description: "Deep crimson — netherrack and magma",
    primaryColor: "#ff4422",
    backgroundColor: "#1a0808",
    textColor: "#ffd0b0",
    fontFamily: "var(--font-mc), monospace",
    isDefault: false,
  },
  {
    name: "Ocean Monument",
    description: "Deep sea — prismarine and dark water",
    primaryColor: "#20d4e8",
    backgroundColor: "#050f1a",
    textColor: "#b0f0ff",
    fontFamily: "var(--font-mc), monospace",
    isDefault: false,
  },
  {
    name: "End Cities",
    description: "Void purple — endstone and chorus",
    primaryColor: "#b060ff",
    backgroundColor: "#0a0512",
    textColor: "#e8d0ff",
    fontFamily: "var(--font-mc), monospace",
    isDefault: false,
  },
  {
    name: "Forest Biome",
    description: "Overgrown green — oak and leaves",
    primaryColor: "#3a9828",
    backgroundColor: "#0a1408",
    textColor: "#d0f0b0",
    fontFamily: "var(--font-mc), monospace",
    isDefault: false,
  },
  {
    name: "Desert Temple",
    description: "Warm sandstone — mesa and gold",
    primaryColor: "#e8a020",
    backgroundColor: "#1a1408",
    textColor: "#f5e8cc",
    fontFamily: "var(--font-mc), monospace",
    isDefault: false,
  },
  {
    name: "Ice Plains",
    description: "Frozen tundra — packed ice and snow",
    primaryColor: "#88ccff",
    backgroundColor: "#0a0e14",
    textColor: "#d0eeff",
    fontFamily: "var(--font-mc), monospace",
    isDefault: false,
  },
];
